// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addNumberAvailability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNumberAvailability));
        
        string IMigrationMetadata.Id
        {
            get { return "202001061010305_addNumberAvailability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
